(prelude-require-packages '(centered-cursor-mode
                            doom-modeline
                            evil-cleverparens
                            evil-commentary
                            evil-exchange
                            evil-fringe-mark
                            evil-leader
                            evil-lion
                            evil-mc
                            evil-quickscope
                            general
                            highlight-indent-guides
                            highlight-thing
                            org-bullets
                            prettier-js
                            psession
                            restart-emacs
                            rjsx-mode
                            window-purpose
                            zerodark-theme))
