(prelude-require-packages '(adoc-mode
                            centered-cursor-mode
                            clj-refactor
                            deadgrep
                            doom-modeline
                            evil-anzu
                            evil-cleverparens
                            evil-commentary
                            evil-exchange
                            evil-fringe-mark
                            evil-leader
                            evil-lion
                            evil-mc
                            evil-owl
                            evil-quickscope
                            evil-traces
                            general
                            highlight-indent-guides
                            highlight-thing
                            org-bullets
                            prettier-js
                            psession
                            restart-emacs
                            rjsx-mode
                            smex
                            window-purpose
                            zerodark-theme))
